//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N1MM_DXK_GW {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("N1MM_DXK_GW.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string AboutClose {
            get {
                return ResourceManager.GetString("AboutClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy details.
        /// </summary>
        public static string AboutCopyProfile {
            get {
                return ResourceManager.GetString("AboutCopyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free software under the GNU General Public License, version 3 or later, with ABSOLUTELY NO WARRANTY..
        /// </summary>
        public static string AboutLicenceShort {
            get {
                return ResourceManager.GetString("AboutLicenceShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutLink {
            get {
                return ResourceManager.GetString("AboutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rewrite of the original VB6 gateway. The DXLab Suite message formats are the work of AA6YQ..
        /// </summary>
        public static string AboutOriginal {
            get {
                return ResourceManager.GetString("AboutOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details copied to the clipboard..
        /// </summary>
        public static string AboutProfileCopied {
            get {
                return ResourceManager.GetString("AboutProfileCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carries QSOs from TR4W and N1MM Logger+ into DXKeeper, and asks DXView and Pathfinder about the callsigns you work..
        /// </summary>
        public static string AboutPurpose {
            get {
                return ResourceManager.GetString("AboutPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About N1MM-DXKeeper Gateway.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation into {0} by {1}.
        /// </summary>
        public static string AboutTranslationBy {
            get {
                return ResourceManager.GetString("AboutTranslationBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contactdelete for {0}: missing callsign or timestamp - nothing was sent to DXKeeper.
        /// </summary>
        public static string AlertDeleteNoKey {
            get {
                return ResourceManager.GetString("AlertDeleteNoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNAL ERROR handling a message ({0}: {1}) - see ErrorLog.txt. The gateway is still running..
        /// </summary>
        public static string AlertInternalError {
            get {
                return ResourceManager.GetString("AlertInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID: {0}.
        /// </summary>
        public static string AlertInvalidMessage {
            get {
                return ResourceManager.GetString("AlertInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - starting WITHOUT multicast..
        /// </summary>
        public static string AlertMulticastRejected {
            get {
                return ResourceManager.GetString("AlertMulticastRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverted the multicast group to &quot;{0}&quot;..
        /// </summary>
        public static string AlertMulticastReverted {
            get {
                return ResourceManager.GetString("AlertMulticastReverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXKeeper did not confirm {0}{1}{2}: {3}.
        /// </summary>
        public static string AlertNotConfirmed {
            get {
                return ResourceManager.GetString("AlertNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - AND it could not be saved to {0}.
        /// </summary>
        public static string AlertNotSavedTo {
            get {
                return ResourceManager.GetString("AlertNotSavedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** {0}: DXKeeper DELETED the original but did not log the edit{1} - the edited QSO is in {2}, import it. Reason: {3}.
        /// </summary>
        public static string AlertReplaceLostQso {
            get {
                return ResourceManager.GetString("AlertReplaceLostQso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** {0}: DXKeeper DELETED the original, the edit was not logged{1}, AND the edit could not be saved to {2}. Reason: {3}.
        /// </summary>
        public static string AlertReplaceLostQsoNotSaved {
            get {
                return ResourceManager.GetString("AlertReplaceLostQsoNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contactreplace for {0}: no usable &lt;oldcall&gt;/&lt;oldtimestamp&gt; - the edit was NOT applied to DXKeeper.
        /// </summary>
        public static string AlertReplaceNoKey {
            get {
                return ResourceManager.GetString("AlertReplaceNoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - saved to {0}.
        /// </summary>
        public static string AlertSavedTo {
            get {
                return ResourceManager.GetString("AlertSavedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverted to UDP port {0}..
        /// </summary>
        public static string AlertUdpPortReverted {
            get {
                return ResourceManager.GetString("AlertUdpPortReverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N1MM-DXKeeper Gateway.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Callbook.
        /// </summary>
        public static string CheckCallbook {
            get {
                return ResourceManager.GetString("CheckCallbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct DXKeeper to query its selected callbook.
        /// </summary>
        public static string CheckCallbookTip {
            get {
                return ResourceManager.GetString("CheckCallbookTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to Club Log.
        /// </summary>
        public static string CheckClubLog {
            get {
                return ResourceManager.GetString("CheckClubLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct DXKeeper to upload logged QSO to Club Log.
        /// </summary>
        public static string CheckClubLogTip {
            get {
                return ResourceManager.GetString("CheckClubLogTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log debugging information.
        /// </summary>
        public static string CheckDebugLogging {
            get {
                return ResourceManager.GetString("CheckDebugLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log debugging information to ErrorLog.txt.
        /// </summary>
        public static string CheckDebugLoggingTip {
            get {
                return ResourceManager.GetString("CheckDebugLoggingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup previous QSOs.
        /// </summary>
        public static string CheckDxkLookup {
            get {
                return ResourceManager.GetString("CheckDxkLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct DXKeeper to display previous QSOs with the logged callsign.
        /// </summary>
        public static string CheckDxkLookupTip {
            get {
                return ResourceManager.GetString("CheckDxkLookupTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to eQSL.cc.
        /// </summary>
        public static string CheckEqsl {
            get {
                return ResourceManager.GetString("CheckEqsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct DXKeeper to upload logged QSO to eQSL.cc.
        /// </summary>
        public static string CheckEqslTip {
            get {
                return ResourceManager.GetString("CheckEqslTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to LoTW.
        /// </summary>
        public static string CheckLotw {
            get {
                return ResourceManager.GetString("CheckLotw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct DXKeeper to upload logged QSO to LoTW.
        /// </summary>
        public static string CheckLotwTip {
            get {
                return ResourceManager.GetString("CheckLotwTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose logging.
        /// </summary>
        public static string CheckVerboseLogging {
            get {
                return ResourceManager.GetString("CheckVerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show low-priority status events in the operation log (e.g. DDE connect/disconnect).
        /// </summary>
        public static string CheckVerboseLoggingTip {
            get {
                return ResourceManager.GetString("CheckVerboseLoggingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string DiagnosticsHeader {
            get {
                return ResourceManager.GetString("DiagnosticsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Error Log.
        /// </summary>
        public static string DisplayErrorLog {
            get {
                return ResourceManager.GetString("DisplayErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N1MM-DXKeeper Gateway is already running..
        /// </summary>
        public static string DlgAlreadyRunning {
            get {
                return ResourceManager.GetString("DlgAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open ErrorLog.txt:
        ///
        ///{0}.
        /// </summary>
        public static string DlgCouldNotOpenErrorLog {
            get {
                return ResourceManager.GetString("DlgCouldNotOpenErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open {0}:
        ///
        ///{1}
        ///
        ///Use the folder link and import the file into DXKeeper from there..
        /// </summary>
        public static string DlgCouldNotOpenFile {
            get {
                return ResourceManager.GetString("DlgCouldNotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the folder:
        ///
        ///{0}.
        /// </summary>
        public static string DlgCouldNotOpenFolder {
            get {
                return ResourceManager.GetString("DlgCouldNotOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the help page:
        ///
        ///{0}.
        /// </summary>
        public static string DlgCouldNotOpenHelp {
            get {
                return ResourceManager.GetString("DlgCouldNotOpenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the licence file:
        ///
        ///{0}.
        /// </summary>
        public static string DlgCouldNotOpenLicence {
            get {
                return ResourceManager.GetString("DlgCouldNotOpenLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The licence file is not where it should be:
        ///
        ///{0}
        ///
        ///This program is free software under the GNU General Public License version 3 or later, and comes with ABSOLUTELY NO WARRANTY. You can read the licence at https://www.gnu.org/licenses/gpl-3.0.html.
        /// </summary>
        public static string DlgLicenceMissing {
            get {
                return ResourceManager.GetString("DlgLicenceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        ///
        ///Leave this blank unless the sending program is configured to send to a multicast group..
        /// </summary>
        public static string DlgMulticastInvalid {
            get {
                return ResourceManager.GetString("DlgMulticastInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing has been written to the error log yet:
        ///
        ///{0}.
        /// </summary>
        public static string DlgNoErrorLog {
            get {
                return ResourceManager.GetString("DlgNoErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every QSO this session was delivered to DXKeeper.
        ///
        ///{0} does not exist..
        /// </summary>
        public static string DlgNoFailedQsos {
            get {
                return ResourceManager.GetString("DlgNoFailedQsos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UDP listening port must be a whole number between 1 and 65535..
        /// </summary>
        public static string DlgUdpPortInvalid {
            get {
                return ResourceManager.GetString("DlgUdpPortInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config &gt; Defaults tab &gt; Network Service.
        /// </summary>
        public static string DxKeeperConfigNetworkService {
            get {
                return ResourceManager.GetString("DxKeeperConfigNetworkService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config &gt; Defaults tab &gt; Network Service &gt; Base Port.
        /// </summary>
        public static string DxKeeperConfigPath {
            get {
                return ResourceManager.GetString("DxKeeperConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXKeeper TCP base port:.
        /// </summary>
        public static string DxKeeperPortLabel {
            get {
                return ResourceManager.GetString("DxKeeperPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (reading from registry…).
        /// </summary>
        public static string DxKeeperPortReading {
            get {
                return ResourceManager.GetString("DxKeeperPortReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only here. Set it in DXKeeper: {0}. The gateway sends to Base Port + 1, which is the port DXKeeper shows in that panel&apos;s heading..
        /// </summary>
        public static string DxKeeperPortTip {
            get {
                return ResourceManager.GetString("DxKeeperPortTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid IP address.
        /// </summary>
        public static string ErrNotAnIpAddress {
            get {
                return ResourceManager.GetString("ErrNotAnIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not an IPv4 multicast address (224.0.0.0 - 239.255.255.255).
        /// </summary>
        public static string ErrNotMulticast {
            get {
                return ResourceManager.GetString("ErrNotMulticast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to another send had not finished yet.
        /// </summary>
        public static string FailBusy {
            get {
                return ResourceManager.GetString("FailBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot connect to DXKeeper on TCP port {0}; in DXKeeper, check that {1} reports &quot;Listening&quot;.
        /// </summary>
        public static string FailConnectRefused {
            get {
                return ResourceManager.GetString("FailConnectRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the connection to DXKeeper timed out after {0} seconds.
        /// </summary>
        public static string FailConnectTimeout {
            get {
                return ResourceManager.GetString("FailConnectTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} QSOs from this session could not be delivered to DXKeeper. Import {1} into DXKeeper, then delete it — this notice clears when the file is gone..
        /// </summary>
        public static string FailedQsoBarMessage {
            get {
                return ResourceManager.GetString("FailedQsoBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 QSO from this session could not be delivered to DXKeeper. Import {0} into DXKeeper, then delete it — this notice clears when the file is gone..
        /// </summary>
        public static string FailedQsoBarMessageOne {
            get {
                return ResourceManager.GetString("FailedQsoBarMessageOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSOs not delivered.
        /// </summary>
        public static string FailedQsoBarTitle {
            get {
                return ResourceManager.GetString("FailedQsoBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} QSOs not delivered — open.
        /// </summary>
        public static string FailedQsoCount {
            get {
                return ResourceManager.GetString("FailedQsoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 QSO not delivered — open.
        /// </summary>
        public static string FailedQsoCountOne {
            get {
                return ResourceManager.GetString("FailedQsoCountOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        public static string FailedQsoOpenFile {
            get {
                return ResourceManager.GetString("FailedQsoOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folder.
        /// </summary>
        public static string FailedQsoOpenFolder {
            get {
                return ResourceManager.GetString("FailedQsoOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import {0} into DXKeeper, then delete it. This count clears when the file is gone..
        /// </summary>
        public static string FailedQsoTip {
            get {
                return ResourceManager.GetString("FailedQsoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXKeeper never closed the connection within {0} seconds, so the QSO may never have been accepted.
        /// </summary>
        public static string FailNoPeerClose {
            get {
                return ResourceManager.GetString("FailNoPeerClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the send failed.
        /// </summary>
        public static string FailSendFailed {
            get {
                return ResourceManager.GetString("FailSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the gateway was shutting down and this was never sent.
        /// </summary>
        public static string FailShuttingDown {
            get {
                return ResourceManager.GetString("FailShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralHeader {
            get {
                return ResourceManager.GetString("GeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Windows.
        /// </summary>
        public static string LanguageFollowWindows {
            get {
                return ResourceManager.GetString("LanguageFollowWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the gateway to switch the interface to {0}..
        /// </summary>
        public static string LanguageRestartNote {
            get {
                return ResourceManager.GetString("LanguageRestartNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language of this window. &quot;Follow Windows&quot; uses the Windows display language. A change takes effect the next time the gateway starts..
        /// </summary>
        public static string LanguageTip {
            get {
                return ResourceManager.GetString("LanguageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string LogClear {
            get {
                return ResourceManager.GetString("LogClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the on-screen log. ErrorLog.txt is not affected..
        /// </summary>
        public static string LogClearTip {
            get {
                return ResourceManager.GetString("LogClearTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation log copied to the clipboard ({0} lines)..
        /// </summary>
        public static string LogCopied {
            get {
                return ResourceManager.GetString("LogCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string LogCopy {
            get {
                return ResourceManager.GetString("LogCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the operation log to the clipboard.
        /// </summary>
        public static string LogCopyTip {
            get {
                return ResourceManager.GetString("LogCopyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Log.
        /// </summary>
        public static string LogHeader {
            get {
                return ResourceManager.GetString("LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not listen on UDP port {0}: {1}.
        /// </summary>
        public static string MsgBindFailed {
            get {
                return ResourceManager.GetString("MsgBindFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multicast group (optional):.
        /// </summary>
        public static string MulticastLabel {
            get {
                return ResourceManager.GetString("MulticastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blank = no multicast.
        /// </summary>
        public static string MulticastPlaceholder {
            get {
                return ResourceManager.GetString("MulticastPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. Leave blank unless the sending program is configured to send to a multicast group (224.0.0.0 - 239.255.255.255). Unicast and broadcast are received either way. The group is joined on the interface the routing table selects..
        /// </summary>
        public static string MulticastTip {
            get {
                return ResourceManager.GetString("MulticastTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string NetworkHeader {
            get {
                return ResourceManager.GetString("NetworkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N1MM-DXKeeper Gateway is free software under the GNU General Public License, version 3 or later. You may use it for any purpose, study how it works, share it, and change it..
        /// </summary>
        public static string NoticeFreeSoftware {
            get {
                return ResourceManager.GetString("NoticeFreeSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free software, and no warranty.
        /// </summary>
        public static string NoticeHeading {
            get {
                return ResourceManager.GetString("NoticeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this program.
        /// </summary>
        public static string NoticeTitle {
            get {
                return ResourceManager.GetString("NoticeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand.
        /// </summary>
        public static string NoticeUnderstood {
            get {
                return ResourceManager.GetString("NoticeUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the licence.
        /// </summary>
        public static string NoticeViewLicence {
            get {
                return ResourceManager.GetString("NoticeViewLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It comes with ABSOLUTELY NO WARRANTY. It is offered in the hope that it is useful, but nobody guarantees it is fit for any particular purpose, and no contributor is liable for anything that goes wrong. Your log is your responsibility: check that QSOs reach DXKeeper..
        /// </summary>
        public static string NoticeWarranty {
            get {
                return ResourceManager.GetString("NoticeWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full licence is in the file COPYING.txt next to the program, and is always available from the About link in the window..
        /// </summary>
        public static string NoticeWhereToFind {
            get {
                return ResourceManager.GetString("NoticeWhereToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string OpenFileButton {
            get {
                return ResourceManager.GetString("OpenFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenFolderButton {
            get {
                return ResourceManager.GetString("OpenFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see ErrorLog.
        /// </summary>
        public static string SeeErrorLog {
            get {
                return ResourceManager.GetString("SeeErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ServicesHeader {
            get {
                return ResourceManager.GetString("ServicesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Status.
        /// </summary>
        public static string StatusHeader {
            get {
                return ResourceManager.GetString("StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tom Schaefer, NY4I.
        /// </summary>
        public static string TranslatedBy {
            get {
                return ResourceManager.GetString("TranslatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All QSOs delivered.
        /// </summary>
        public static string TrayAllDelivered {
            get {
                return ResourceManager.GetString("TrayAllDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXKeeper has not confirmed {0} QSOs this session. They are saved for you to import by hand..
        /// </summary>
        public static string TrayFailureMessage {
            get {
                return ResourceManager.GetString("TrayFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSO not delivered.
        /// </summary>
        public static string TrayFailureTitle {
            get {
                return ResourceManager.GetString("TrayFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gateway is still receiving QSOs here. Double-click this icon to bring the window back..
        /// </summary>
        public static string TrayHiddenMessage {
            get {
                return ResourceManager.GetString("TrayHiddenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still running.
        /// </summary>
        public static string TrayHiddenTitle {
            get {
                return ResourceManager.GetString("TrayHiddenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last QSO: {0}.
        /// </summary>
        public static string TrayLastQso {
            get {
                return ResourceManager.GetString("TrayLastQso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged to DXKeeper: {0}.
        /// </summary>
        public static string TrayLogged {
            get {
                return ResourceManager.GetString("TrayLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No QSOs yet.
        /// </summary>
        public static string TrayNoQsoYet {
            get {
                return ResourceManager.GetString("TrayNoQsoYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT delivered: {0}.
        /// </summary>
        public static string TrayNotDelivered {
            get {
                return ResourceManager.GetString("TrayNotDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the undelivered QSO file.
        /// </summary>
        public static string TrayOpenFailedFile {
            get {
                return ResourceManager.GetString("TrayOpenFailedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show it in its folder.
        /// </summary>
        public static string TrayOpenFailedFolder {
            get {
                return ResourceManager.GetString("TrayOpenFailedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to send: {0}.
        /// </summary>
        public static string TrayQueued {
            get {
                return ResourceManager.GetString("TrayQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit the gateway.
        /// </summary>
        public static string TrayQuit {
            get {
                return ResourceManager.GetString("TrayQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received from N1MM: {0}.
        /// </summary>
        public static string TrayReceived {
            get {
                return ResourceManager.GetString("TrayReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the gateway window.
        /// </summary>
        public static string TrayShow {
            get {
                return ResourceManager.GetString("TrayShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received {0}, logged {1}, not delivered {2}.
        /// </summary>
        public static string TrayTooltip {
            get {
                return ResourceManager.GetString("TrayTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP listening port:.
        /// </summary>
        public static string UdpPortLabel {
            get {
                return ResourceManager.GetString("UdpPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP port that N1MM Logger+ broadcasts QSO XML to (default 12060).
        /// </summary>
        public static string UdpPortTip {
            get {
                return ResourceManager.GetString("UdpPortTip", resourceCulture);
            }
        }
    }
}
