//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N1MM_DXK_GW {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("N1MM_DXK_GW.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N1MM-DXKeeper Gateway.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Callbook.
        /// </summary>
        public static string CheckCallbook {
            get {
                return ResourceManager.GetString("CheckCallbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct DXKeeper to query its selected callbook.
        /// </summary>
        public static string CheckCallbookTip {
            get {
                return ResourceManager.GetString("CheckCallbookTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to Club Log.
        /// </summary>
        public static string CheckClubLog {
            get {
                return ResourceManager.GetString("CheckClubLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct DXKeeper to upload logged QSO to Club Log.
        /// </summary>
        public static string CheckClubLogTip {
            get {
                return ResourceManager.GetString("CheckClubLogTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log debugging information.
        /// </summary>
        public static string CheckDebugLogging {
            get {
                return ResourceManager.GetString("CheckDebugLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log debugging information to ErrorLog.txt.
        /// </summary>
        public static string CheckDebugLoggingTip {
            get {
                return ResourceManager.GetString("CheckDebugLoggingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup previous QSOs.
        /// </summary>
        public static string CheckDxkLookup {
            get {
                return ResourceManager.GetString("CheckDxkLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct DXKeeper to display previous QSOs with the logged callsign.
        /// </summary>
        public static string CheckDxkLookupTip {
            get {
                return ResourceManager.GetString("CheckDxkLookupTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to eQSL.cc.
        /// </summary>
        public static string CheckEqsl {
            get {
                return ResourceManager.GetString("CheckEqsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct DXKeeper to upload logged QSO to eQSL.cc.
        /// </summary>
        public static string CheckEqslTip {
            get {
                return ResourceManager.GetString("CheckEqslTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload to LoTW.
        /// </summary>
        public static string CheckLotw {
            get {
                return ResourceManager.GetString("CheckLotw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct DXKeeper to upload logged QSO to LoTW.
        /// </summary>
        public static string CheckLotwTip {
            get {
                return ResourceManager.GetString("CheckLotwTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose logging.
        /// </summary>
        public static string CheckVerboseLogging {
            get {
                return ResourceManager.GetString("CheckVerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show low-priority status events in the operation log (e.g. DDE connect/disconnect).
        /// </summary>
        public static string CheckVerboseLoggingTip {
            get {
                return ResourceManager.GetString("CheckVerboseLoggingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string DiagnosticsHeader {
            get {
                return ResourceManager.GetString("DiagnosticsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Error Log.
        /// </summary>
        public static string DisplayErrorLog {
            get {
                return ResourceManager.GetString("DisplayErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config &gt; Defaults tab &gt; Network Service &gt; Base Port.
        /// </summary>
        public static string DxKeeperConfigPath {
            get {
                return ResourceManager.GetString("DxKeeperConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXKeeper TCP base port:.
        /// </summary>
        public static string DxKeeperPortLabel {
            get {
                return ResourceManager.GetString("DxKeeperPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (reading from registry…).
        /// </summary>
        public static string DxKeeperPortReading {
            get {
                return ResourceManager.GetString("DxKeeperPortReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only here. Set it in DXKeeper: {0}. The gateway sends to Base Port + 1, which is the port DXKeeper shows in that panel&apos;s heading..
        /// </summary>
        public static string DxKeeperPortTip {
            get {
                return ResourceManager.GetString("DxKeeperPortTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} QSOs from this session could not be delivered to DXKeeper. Import {1} into DXKeeper, then delete it — this notice clears when the file is gone..
        /// </summary>
        public static string FailedQsoBarMessage {
            get {
                return ResourceManager.GetString("FailedQsoBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 QSO from this session could not be delivered to DXKeeper. Import {0} into DXKeeper, then delete it — this notice clears when the file is gone..
        /// </summary>
        public static string FailedQsoBarMessageOne {
            get {
                return ResourceManager.GetString("FailedQsoBarMessageOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QSOs not delivered.
        /// </summary>
        public static string FailedQsoBarTitle {
            get {
                return ResourceManager.GetString("FailedQsoBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} QSOs not delivered — open.
        /// </summary>
        public static string FailedQsoCount {
            get {
                return ResourceManager.GetString("FailedQsoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 QSO not delivered — open.
        /// </summary>
        public static string FailedQsoCountOne {
            get {
                return ResourceManager.GetString("FailedQsoCountOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        public static string FailedQsoOpenFile {
            get {
                return ResourceManager.GetString("FailedQsoOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folder.
        /// </summary>
        public static string FailedQsoOpenFolder {
            get {
                return ResourceManager.GetString("FailedQsoOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import {0} into DXKeeper, then delete it. This count clears when the file is gone..
        /// </summary>
        public static string FailedQsoTip {
            get {
                return ResourceManager.GetString("FailedQsoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string LogClear {
            get {
                return ResourceManager.GetString("LogClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the on-screen log. ErrorLog.txt is not affected..
        /// </summary>
        public static string LogClearTip {
            get {
                return ResourceManager.GetString("LogClearTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation log copied to the clipboard ({0} lines)..
        /// </summary>
        public static string LogCopied {
            get {
                return ResourceManager.GetString("LogCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string LogCopy {
            get {
                return ResourceManager.GetString("LogCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the operation log to the clipboard.
        /// </summary>
        public static string LogCopyTip {
            get {
                return ResourceManager.GetString("LogCopyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Log.
        /// </summary>
        public static string LogHeader {
            get {
                return ResourceManager.GetString("LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multicast group (optional):.
        /// </summary>
        public static string MulticastLabel {
            get {
                return ResourceManager.GetString("MulticastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blank = no multicast.
        /// </summary>
        public static string MulticastPlaceholder {
            get {
                return ResourceManager.GetString("MulticastPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional. Leave blank unless the sending program is configured to send to a multicast group (224.0.0.0 - 239.255.255.255). Unicast and broadcast are received either way. The group is joined on the interface the routing table selects..
        /// </summary>
        public static string MulticastTip {
            get {
                return ResourceManager.GetString("MulticastTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string NetworkHeader {
            get {
                return ResourceManager.GetString("NetworkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string OpenFileButton {
            get {
                return ResourceManager.GetString("OpenFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenFolderButton {
            get {
                return ResourceManager.GetString("OpenFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see ErrorLog.
        /// </summary>
        public static string SeeErrorLog {
            get {
                return ResourceManager.GetString("SeeErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ServicesHeader {
            get {
                return ResourceManager.GetString("ServicesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Status.
        /// </summary>
        public static string StatusHeader {
            get {
                return ResourceManager.GetString("StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP listening port:.
        /// </summary>
        public static string UdpPortLabel {
            get {
                return ResourceManager.GetString("UdpPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP port that N1MM Logger+ broadcasts QSO XML to (default 12060).
        /// </summary>
        public static string UdpPortTip {
            get {
                return ResourceManager.GetString("UdpPortTip", resourceCulture);
            }
        }
    }
}
